#use swe3613_db02p2;
set foreign_key_checks=0;
TRUNCATE tbl_user;
TRUNCATE tbl_artist;
TRUNCATE tbl_genre;
TRUNCATE tbl_mixtape;
TRUNCATE tbl_song;
TRUNCATE tbl_song_artist;
TRUNCATE tbl_song_genre;
set foreign_key_checks=1;

INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user01', 'pass', 'fake1@fake.com', '0', 'Bob1', 'Smith1');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user02', 'pass', 'fake2@fake.com', '0', 'Bob2', 'Smith2');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user03', 'pass', 'fake3@fake.com', '0', 'Bob3', 'Smith3');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user04', 'pass', 'fake@4fake.com', '0', 'Bob4', 'Smith4');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user05', 'pass', 'fake5@fake.com', '0', 'Bob5', 'Smith5');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user06', 'pass', 'fake6@fake.com', '0', 'Bob6', 'Smith6');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user07', 'pass', 'fake7@fake.com', '0', 'Bob7', 'Smith7');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user08', 'pass', 'fake8@fake.com', '0', 'Bob8', 'Smith8');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user09', 'pass', 'fake9@fake.com', '0', 'Bob9', 'Smith9');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user10', 'pass', 'fake10@fake.com', '0', 'Bob10', 'Smith10');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user11', 'pass', 'fake11@fake.com', '0', 'Bob11', 'Smith11');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user12', 'pass', 'fake12@fake.com', '0', 'Bob12', 'Smith12');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user13', 'pass', 'fake13@fake.com', '0', 'Bob13', 'Smith13');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user14', 'pass', 'fake14@fake.com', '0', 'Bob14', 'Smith14');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `first_name`, `last_name`) VALUES ('user15', 'pass', 'fake15@fake.com', '0', 'Bob15', 'Smith15');
INSERT INTO `swe3613_db02p2`.`tbl_user` (`login`, `password`, `email`, `admin`, `secret_question`,`secret_answer`,`first_name`, `last_name`) VALUES ('exampleuser', 'examplepassword', 'example@email.com', '0', 'whatisthis', 'anexample', 'examplefirst', 'examplelast');

INSERT INTO `swe3613_db02p2`.`tbl_genre` (`name`) VALUES ('Symphonic Power Metal');
INSERT INTO `swe3613_db02p2`.`tbl_genre` (`name`) VALUES ('Rock');
INSERT INTO `swe3613_db02p2`.`tbl_genre` (`name`) VALUES ('Pop');
INSERT INTO `swe3613_db02p2`.`tbl_genre` (`name`) VALUES ('Jazz');
INSERT INTO `swe3613_db02p2`.`tbl_genre` (`name`) VALUES ('Kpop');

INSERT INTO `swe3613_db02p2`.`tbl_artist` (`name`) VALUES ('Artist1');
INSERT INTO `swe3613_db02p2`.`tbl_artist` (`name`) VALUES ('Artist2');
INSERT INTO `swe3613_db02p2`.`tbl_artist` (`name`) VALUES ('Artist3');
INSERT INTO `swe3613_db02p2`.`tbl_artist` (`name`) VALUES ('Norazo');

INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Rock1',0);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Jazz1',1);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Pop1',1);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Symphonic Power Metal1',1);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Rock2',1);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Pop2',1);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Jazz2',1);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Rock Pop1',0);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Rock Pop2',1);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Jazz3',1);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Pop Jazz Rock1',1);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Symphonic Power Metal2',1);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Symphonic Power Metal Rock3',1);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Rock4',0);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Rock5',0);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Rock6',0);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Rock7',0);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Rock8',0);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Rock9',0);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`) VALUES ('Pop4',1);
INSERT INTO `swe3613_db02p2`.`tbl_song` (`title`,`approved`,`flagged`,`youtube`,`youtube_approved`) VALUES ('Wild Horse',1,0,'https://www.youtube.com/watch?v=hX3O5v-ylC4',1);

INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('1', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('2', '4');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('3', '3');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('4', '1');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('5', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('6', '3');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('7', '4');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('8', '2');INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('8', '3');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('9', '2');INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('9', '3');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('10', '4');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('11', '2');INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('11', '3');INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('11', '4');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('12', '1');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('13', '1');INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('13', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('14', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('15', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('16', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('17', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('18', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('19', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('20', '3');
INSERT INTO `swe3613_db02p2`.`tbl_song_genre` (`song_id`, `genre_id`) VALUES ('21', '5');

INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('1', '1');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('2', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('3', '3');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('4', '1');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('5', '1');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('6', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('7', '3');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('8', '1');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('8', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('9', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('9', '3');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('10', '3');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('11', '1');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('11', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('11', '3');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('12', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('13', '3');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('13', '1');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('14', '1');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('15', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('16', '3');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('17', '1');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('18', '2');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('19', '3');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('20', '1');
INSERT INTO `swe3613_db02p2`.`tbl_song_artist` (`song_id`, `artist_id`) VALUES ('21', '4');

INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('1', '1', '2');
INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('1', '2', '4');
INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('1', '3', '3');
INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('1', '4', '1');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('1', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('1', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('1', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('1', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('1', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('1', '', '');
INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('2', '4', '1');
INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('2', '12', '2');
INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('2', '13', '3');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('2', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('2', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('2', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('2', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('2', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('2', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('2', '', '');
INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('3', '4', '1');
INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('3', '12', '3');
INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('3', '13', '6');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('3', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('3', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('3', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('3', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('3', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('3', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('3', '', '');
INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('4', '4', '1');
INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('4', '12', '9');
INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('4', '13', '2');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('4', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('4', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('4', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('4', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('4', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('4', '', '');
#INSERT INTO `swe3613_db02p2`.`tbl_mixtape` (`user_id`, `song_id`, `position`) VALUES ('4', '', '');